# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nt8_bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nt8_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10nt8_bridge.proto\x12\tnt8bridge\"\xa4\x01\n\rCandleRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x12\x0c\n\x04time\x18\x07 \x01(\t\x12\x18\n\x10\x63urrent_position\x18\x08 \x01(\x01\x12\x13\n\x0b\x63urrent_pnl\x18\t \x01(\x01\"\x9d\x01\n\x0e\x41\x63tionResponse\x12\x30\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32 .nt8bridge.ActionResponse.Action\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\"4\n\x06\x41\x63tion\x12\x08\n\x04HOLD\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\x12\r\n\tCLOSE_ALL\x10\x03\x32X\n\rStrategyBrain\x12G\n\x0e\x45valuateCandle\x12\x18.nt8bridge.CandleRequest\x1a\x19.nt8bridge.ActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nt8_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDLEREQUEST']._serialized_start=32
  _globals['_CANDLEREQUEST']._serialized_end=196
  _globals['_ACTIONRESPONSE']._serialized_start=199
  _globals['_ACTIONRESPONSE']._serialized_end=356
  _globals['_ACTIONRESPONSE_ACTION']._serialized_start=304
  _globals['_ACTIONRESPONSE_ACTION']._serialized_end=356
  _globals['_STRATEGYBRAIN']._serialized_start=358
  _globals['_STRATEGYBRAIN']._serialized_end=446
# @@protoc_insertion_point(module_scope)
