# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nt8_bridge_pb2 as nt8__bridge__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nt8_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyBrainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateCandle = channel.unary_unary(
                '/nt8bridge.StrategyBrain/EvaluateCandle',
                request_serializer=nt8__bridge__pb2.CandleRequest.SerializeToString,
                response_deserializer=nt8__bridge__pb2.ActionResponse.FromString,
                _registered_method=True)


class StrategyBrainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateCandle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateCandle': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateCandle,
                    request_deserializer=nt8__bridge__pb2.CandleRequest.FromString,
                    response_serializer=nt8__bridge__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nt8bridge.StrategyBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nt8bridge.StrategyBrain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyBrain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateCandle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nt8bridge.StrategyBrain/EvaluateCandle',
            nt8__bridge__pb2.CandleRequest.SerializeToString,
            nt8__bridge__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
